version: '3'

services:
  web:
    image: nginx
    container_name: web
    volumes:
      - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8585:80"
    restart: always
    depends_on:
      - php

  php:
    build: .docker
    container_name: php
    restart: always
    volumes:
      - .:/var/www/html

  composer:
    image: composer
    container_name: composer
    volumes:
      - .:/app
    command: install

  db:
    image: postgres:10.1
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE:-metrics}
      - POSTGRES_USER=${DB_USERNAME:-db_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-db_password}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/